[package]
name = "logaggrd"
version = "0.1.0"
authors = ["Noah Levitt <nlevitt@archive.org>"]
edition = "2018"

[dependencies]
tokio = "0.1.19"
futures = "0.1.26"
tokio-codec = "0.1.1"
tokio-io = "0.1.12"
env_logger = "0.6.1"
bytes = "0.4.12"
clap = "~2.33.0"
tokio-signal = "0.2.7"

